### ISSUE TITLE
Master kubelet not configured with --config=/etc/kubernetes/manifests when security disabled

### ISSUE THREAD

**Issue by icio** [bloomberg/kubernetes-cluster-cookbook#12]
The `--config` option should be specified in both kubelet configs of:

* [security disabled](https://github.com/bloomberg/kubernetes-cluster-cookbook/blob/b9df495389ea1a04fa4f22c9973826e5a7581856/templates/default/kube-kubelet.erb#L8); and
* [security enabled](https://github.com/bloomberg/kubernetes-cluster-cookbook/blob/b9df495389ea1a04fa4f22c9973826e5a7581856/templates/default/kube-kubelet.erb#L14)

**Comment by rapenchukd** [comment]
https://github.com/bloomberg/kubernetes-cluster-cookbook/pull/13
