### ISSUE TITLE
Fix formatting and typo in wiki

### ISSUE THREAD

**Issue by aknuds1** [bloomberg/kubernetes-cluster-cookbook#9]
I've fixed formatting and a typo in [a fork of your wiki](https://github.com/aknuds1/kubernetes-cluster-cookbook-wiki/commit/219632c2f7fc5fbf2aa455cec86c10e222726480).

**Comment by rapenchukd** [comment]
:+1: picking this up now! Thanks!

**Comment by rapenchukd** [comment]
New edits applied to wiki accordingly!
https://github.com/bloomberg/kubernetes-cluster-cookbook/wiki/Beginners-Guide/69c5150b6e8a04bb01a81becf5fe362ae5a444eb

**Comment by aknuds1** [comment]
Looks good!
